package dev.lokeshbisht.cachingWithSpringBoot.enums;

public enum ErrorCode {
    AUTHENTICATION_ERROR,
    AUTHORIZATION_ERROR,
    INVALID_RESOURCE,
    INTERNAL_SERVER_ERROR,
    BAD_REQUEST,
    INSTRUCTOR_NOT_FOUND,
    SUBJECT_NOT_FOUND,
    DEPARTMENT_NOT_FOUND
}
